var SITE_URL = 'https://pulpomasters.com',
SITE_URL_DIR=SITE_URL,
PORT_NODE='8095',
SOCKET_CHAT=SITE_URL+':'+PORT_NODE,
NOMBRE_PAGINA='',
PUBLIC_KEY_CULQI_PRODUCTION='sk_test_SaV9dp9ucC23HArp';
PUBLIC_KEY_CULQI_TEST='pk_test_Al9m93N2aA78oFt6';